name = "sv2"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
[[routes]] = 
pattern = "sv2.xadal.my.id"
custom_domain = true 
[[routes]] = 
pattern = "untar.ac.id.sv2.xadal.my.id"
custom_domain = true 
   
[vars]
#PROXYIP = "211.230.110.231:50008"
UUID = "791aedad-6442-4ac5-a289-c94071150e36"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
